### ISSUE TITLE
get_def_names fails when moving annotate_imports as a test

### ISSUE THREAD

**Issue by lmmx** [lmmx/mvdef#2]
There seems to be something not working for all cases related to registering some variable names within the logic of `get_def_names` in `mvdef.src.ast_util`, which gives the following error:

```
--------------RUNNING src.cli⠶main()--------------
Traceback (most recent call last):
  File "/home/louis/miniconda/envs/mvdef/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/louis/miniconda/envs/mvdef/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/louis/miniconda/envs/mvdef/lib/python3.7/site-packages/mvdef/__main__.py", line 37, in <module>
    run_cli(src_path, dst_path, mvdefs, dry_run, report, backup)
  File "/home/louis/miniconda/envs/mvdef/lib/python3.7/site-packages/mvdef/src/cli.py", line 14, in main
    use_backup=backup,
  File "/home/louis/miniconda/envs/mvdef/lib/python3.7/site-packages/mvdef/src/transfer.py", line 41, in parse_transfer
    src_edits = ast_parse(src_p, mvdefs=mvdefs, report=report)
  File "/home/louis/miniconda/envs/mvdef/lib/python3.7/site-packages/mvdef/src/ast_util.py", line 43, in ast_parse
    edit_agenda = process_ast(fp, mvdefs, trunk, transfers, report)
  File "/home/louis/miniconda/envs/mvdef/lib/python3.7/site-packages/mvdef/src/ast_util.py", line 98, in process_ast
    m_names, nm_names, rm_names = parse_mv_funcs(mvdefs, trunk, report=report)
  File "/home/louis/miniconda/envs/mvdef/lib/python3.7/site-packages/mvdef/src/ast_util.py", line 349, in parse_mv_funcs
    mvdef_names = get_def_names(mvdefs, defs, import_annos, report=report)
  File "/home/louis/miniconda/envs/mvdef/lib/python3.7/site-packages/mvdef/src/ast_util.py", line 285, in get_def_names
    assert unknowns == [], f"These names could not be sourced: {unknowns}"
AssertionError: These names could not be sourced: ['asname', 'ld', 'ln', 'imported_names', 'imp_name_dict', 'd', 'imp_line', 'name', 'imp_no', 'fullname']
```

To reproduce:

```py
mvdef -dr -m "annotate_imports" --src mvdef/src/import_util.py --dst mvdef/src/new_file.py
```

To simplify this debugging, I've moved the `annotate_imports` function to its own file (`test_file.py`) in a separate directory to better focus on just the error here. It can be reproduced there with:

```
mvdef -dr -m "annotate_imports" --src test_file.py --dst new_file.py
```

**Comment by lmmx** [comment]
Resolved in version 0.1.7 :smiley: Happy new year! :fireworks:
